```mermaid
graph TD
  client["Client"]
  
  subgraph Cluster_A["Cluster A"]
    direction TB
    argo["<img src='image.png' width='32'/> Argo CD"]
  end

  subgraph Cluster_B["Cluster B"]
    direction TB
    app_b1["App B1"]
    app_b2["App B2"]
  end

  subgraph Cluster_C["Cluster C"]
    direction TB
    app_c1["App C1"]
    app_c2["App C2"]
  end

  client-- Deploy/Manage -->argo
  argo-- Manages -->app_b1
  argo-- Manages -->app_b2
  argo-- Manages -->app_c1
  argo-- Manages -->app_c2

  %% Styling
  classDef argo fill:#f7f7f7,stroke:#e76f51,stroke-width:3px,color:#e76f51;
  class argo argo;
```
