apiVersion: v1
kind: Pod
metadata:
  name: service-b-app
  labels:
    app: service-b
spec:
  containers:
  - name: service-b-app
    image: registry.k8s.io/e2e-test-images/agnhost:2.39
    command: ["/agnhost", "serve-hostname", "--http=true", "--port=8080"]
---
apiVersion: v1
kind: Service
metadata:
  name: service-b-service
spec:
  selector:
    app: service-b
  ports:
  - port: 8080
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: service-b-ingress
spec:
  rules:
  - host: service-b.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: service-b-service
            port:
              number: 8080
